# Generated by Django 2.2.3 on 2019-07-31 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('stock_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
